/**
 * Terms of Service Screen
 *
 * Displays the app's terms of service.
 */

import React from 'react';
import { Text, StyleSheet, ScrollView } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import type { ProfileStackScreenProps } from '../../types/navigation';
import { colors, spacing } from '../../theme';

type Props = ProfileStackScreenProps<'TermsOfService'>;

/**
 * Terms of Service Screen Component
 */
const TermsOfServiceScreen = (_props: Props) => {
  return (
    <SafeAreaView style={styles.container} edges={['bottom']}>
      <ScrollView
        style={styles.scrollView}
        contentContainerStyle={styles.content}
      >
        <Text style={styles.lastUpdated}>Last Updated: December 2024</Text>

        <Text style={styles.sectionTitle}>1. Acceptance of Terms</Text>
        <Text style={styles.paragraph}>
          By downloading, installing, or using Manifest the Unseen ("the App"),
          you agree to be bound by these Terms of Service. If you do not agree
          to these terms, please do not use the App.
        </Text>

        <Text style={styles.sectionTitle}>2. Description of Service</Text>
        <Text style={styles.paragraph}>
          Manifest the Unseen is a personal development and manifestation app
          that provides structured workbook exercises, AI-guided wisdom,
          meditation practices, and journaling features to help users with
          their personal growth journey.
        </Text>

        <Text style={styles.sectionTitle}>3. User Accounts</Text>
        <Text style={styles.paragraph}>
          To use certain features of the App, you must create an account. You
          are responsible for maintaining the confidentiality of your account
          credentials and for all activities that occur under your account.
          You agree to provide accurate and complete information when creating
          your account.
        </Text>

        <Text style={styles.sectionTitle}>4. Subscriptions and Payments</Text>
        <Text style={styles.paragraph}>
          The App offers subscription-based access to premium features. By
          subscribing, you agree to pay the applicable subscription fees.
          Subscriptions automatically renew unless cancelled at least 24 hours
          before the end of the current period. Payment will be charged to your
          Apple ID account.
        </Text>
        <Text style={styles.bulletPoint}>
          {'\u2022'} Free trial periods may be offered for new subscribers
        </Text>
        <Text style={styles.bulletPoint}>
          {'\u2022'} Refunds are handled according to Apple's App Store policies
        </Text>
        <Text style={styles.bulletPoint}>
          {'\u2022'} Prices may vary by region and are subject to change
        </Text>

        <Text style={styles.sectionTitle}>5. User Content</Text>
        <Text style={styles.paragraph}>
          You retain ownership of content you create within the App, including
          journal entries, workbook responses, and vision boards. By using the
          App, you grant us a limited license to store and process your content
          solely for the purpose of providing our services to you.
        </Text>

        <Text style={styles.sectionTitle}>6. AI Features Disclaimer</Text>
        <Text style={styles.paragraph}>
          The App includes AI-powered features for guidance and recommendations.
          These features are provided for informational and inspirational purposes
          only and should not be considered professional advice. The AI responses
          are generated by artificial intelligence and may not always be accurate
          or appropriate for your specific situation.
        </Text>

        <Text style={styles.sectionTitle}>7. Prohibited Uses</Text>
        <Text style={styles.paragraph}>
          You agree not to:
        </Text>
        <Text style={styles.bulletPoint}>
          {'\u2022'} Use the App for any illegal purpose
        </Text>
        <Text style={styles.bulletPoint}>
          {'\u2022'} Attempt to gain unauthorized access to the App or its systems
        </Text>
        <Text style={styles.bulletPoint}>
          {'\u2022'} Interfere with other users' use of the App
        </Text>
        <Text style={styles.bulletPoint}>
          {'\u2022'} Reverse engineer or attempt to extract source code
        </Text>
        <Text style={styles.bulletPoint}>
          {'\u2022'} Use the App to transmit harmful or malicious content
        </Text>

        <Text style={styles.sectionTitle}>8. Intellectual Property</Text>
        <Text style={styles.paragraph}>
          The App and its content, including but not limited to text, graphics,
          logos, images, audio, and software, are the property of Lunar Rivers
          and are protected by copyright and other intellectual property laws.
          The workbook methodology, meditation content, and AI training data
          are proprietary and may not be reproduced without permission.
        </Text>

        <Text style={styles.sectionTitle}>9. Disclaimer of Warranties</Text>
        <Text style={styles.paragraph}>
          The App is provided "as is" without warranties of any kind. We do not
          guarantee that the App will be uninterrupted, error-free, or secure.
          We are not responsible for any damages resulting from your use of
          the App.
        </Text>

        <Text style={styles.sectionTitle}>10. Limitation of Liability</Text>
        <Text style={styles.paragraph}>
          To the maximum extent permitted by law, Lunar Rivers shall not be
          liable for any indirect, incidental, special, consequential, or
          punitive damages arising from your use of the App.
        </Text>

        <Text style={styles.sectionTitle}>11. Termination</Text>
        <Text style={styles.paragraph}>
          We may terminate or suspend your access to the App at any time,
          without prior notice, for conduct that we believe violates these
          Terms or is harmful to other users of the App, us, or third parties.
        </Text>

        <Text style={styles.sectionTitle}>12. Changes to Terms</Text>
        <Text style={styles.paragraph}>
          We reserve the right to modify these Terms at any time. We will
          notify users of significant changes through the App. Your continued
          use of the App after changes constitutes acceptance of the modified
          Terms.
        </Text>

        <Text style={styles.sectionTitle}>13. Governing Law</Text>
        <Text style={styles.paragraph}>
          These Terms shall be governed by and construed in accordance with
          the laws of the United States, without regard to conflict of law
          principles.
        </Text>

        <Text style={styles.sectionTitle}>14. Contact</Text>
        <Text style={styles.paragraph}>
          For questions about these Terms of Service, please contact us at:
          jimmy@agenticpersonnel.com
        </Text>
      </ScrollView>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background.primary,
  },
  scrollView: {
    flex: 1,
  },
  content: {
    padding: spacing.md,
    paddingBottom: spacing['2xl'],
  },
  lastUpdated: {
    fontSize: 13,
    color: colors.text.tertiary,
    marginBottom: spacing.lg,
    fontStyle: 'italic',
  },
  sectionTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: colors.text.primary,
    marginTop: spacing.lg,
    marginBottom: spacing.sm,
  },
  paragraph: {
    fontSize: 15,
    color: colors.text.secondary,
    lineHeight: 22,
    marginBottom: spacing.sm,
  },
  bulletPoint: {
    fontSize: 15,
    color: colors.text.secondary,
    lineHeight: 22,
    paddingLeft: spacing.md,
    marginBottom: spacing.xs,
  },
});

export default TermsOfServiceScreen;
